### ISSUE TITLE
Unhandled promise rejection starting Kodi ...

### ISSUE THREAD

**Issue by mediaDS** [instalator/ioBroker.kodi#53]
Hi
I use the latest ioBroker on a Odroid C2 micro and each time I startup Kodi it gives me the following error message (not a warn- but a red error message):

```
2021-01-26 23:01:28.454 - info: kodi.0 (1629) KODI connected--
2021-01-26 23:01:32.637 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-01-26 23:01:32.640 - error: kodi.0 (1629) unhandled promise rejection: Cannot read property 'socket' of null
2021-01-26 23:01:32.643 - error: kodi.0 (1629) TypeError: Cannot read property 'socket' of null
at ErrProcessing (/opt/iobroker/node_modules/iobroker.kodi/kodi.js:1143:20)
at /opt/iobroker/node_modules/iobroker.kodi/kodi.js:666:13
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-26 23:01:32.746 - info: kodi.0 (1629) KODI connected
2021-01-26 23:01:32.786 - info: kodi.0 (1629) terminating
2021-01-26 23:01:32.790 - info: kodi.0 (1629) Terminated (NO_ERROR): Without reason
2021-01-26 23:01:33.443 - info: host.Casper instance system.adapter.kodi.0 terminated with code 0 (NO_ERROR)
2021-01-26 23:01:33.455 - info: host.Casper Restart adapter system.adapter.kodi.0 because enabled
2021-01-26 23:02:03.604 - info: host.Casper instance system.adapter.kodi.0 started with pid 3022
2021-01-26 23:02:06.149 - info: kodi.0 (3022) starting. Version 2.0.4 in /opt/iobroker/node_modules/iobroker.kodi, node: v12.20.1, js-controller: 3.1.6
```

Any idea how to fix this or can I just ignore it?

**Comment by instalator** [comment]
Hi, attach the debug log at the time of the error.

**Comment by mediaDS** [comment]
Hello,

and how exactly do I do that? However, I forgot to mention that everything works fine even with the error message. It seems to appear only while Kodi is starting up.

I will have a look on how to enable the Kodi debug log.

**Comment by instalator** [comment]
You need to enable debug for the adapter kodi in the admin panel iob

**Comment by mediaDS** [comment]
Sorry, I just couldn't remember how to enable debug logs :)

Anyway, here it is (I removed unneccessary messages from other adapters):

```
2021-01-27 11:27:04.077  - [32minfo[39m: host.Casper instance system.adapter.kodi.0 started with pid 6233
2021-01-27 11:27:05.578  - [34mdebug[39m: kodi.0 (6233) Redis Objects: Use Redis connection: 0.0.0.0:9001
2021-01-27 11:27:05.671  - [34mdebug[39m: kodi.0 (6233) Objects client ready ... initialize now
2021-01-27 11:27:05.679  - [34mdebug[39m: kodi.0 (6233) Objects create System PubSub Client
2021-01-27 11:27:05.682  - [34mdebug[39m: kodi.0 (6233) Objects create User PubSub Client
2021-01-27 11:27:05.693  - [34mdebug[39m: kodi.0 (6233) Objects client initialize lua scripts
2021-01-27 11:27:05.747  - [34mdebug[39m: kodi.0 (6233) Objects connected to redis: 0.0.0.0:9001
2021-01-27 11:27:05.761  - [34mdebug[39m: kodi.0 (6233) objectDB connected
2021-01-27 11:27:05.766  - [34mdebug[39m: kodi.0 (6233) Redis States: Use Redis connection: 0.0.0.0:9000
2021-01-27 11:27:05.799  - [34mdebug[39m: kodi.0 (6233) States create User PubSub Client
2021-01-27 11:27:05.846  - [34mdebug[39m: kodi.0 (6233) States create System PubSub Client
2021-01-27 11:27:06.673  - [34mdebug[39m: kodi.0 (6233) States connected to redis: 0.0.0.0:9000
2021-01-27 11:27:06.676  - [34mdebug[39m: kodi.0 (6233) statesDB connected
2021-01-27 11:27:07.695  - [32minfo[39m: kodi.0 (6233) starting. Version 2.0.4 in /opt/iobroker/node_modules/iobroker.kodi, node: v12.20.1, js-controller: 3.1.6
2021-01-27 11:27:12.770  - [34mdebug[39m: kodi.0 (6233) KODI connecting to: James:9090
2021-01-27 11:27:15.806  - [34mdebug[39m: kodi.0 (6233) getConnection Error: Socket error: connect EHOSTUNREACH 10.42.0.4:9090
2021-01-27 11:27:20.809  - [34mdebug[39m: kodi.0 (6233) KODI connecting to: James:9090
2021-01-27 11:27:23.811  - [34mdebug[39m: kodi.0 (6233) getConnection Error: Socket error: connect EHOSTUNREACH 10.42.0.4:9090
2021-01-27 11:27:28.817  - [34mdebug[39m: kodi.0 (6233) KODI connecting to: James:9090
[....]
2021-01-27 11:27:31.832  - [34mdebug[39m: kodi.0 (6233) getConnection Error: Socket error: connect EHOSTUNREACH 10.42.0.4:9090
[....]
2021-01-27 11:27:36.836  - [34mdebug[39m: kodi.0 (6233) KODI connecting to: James:9090
2021-01-27 11:27:37.078  - [32minfo[39m: kodi.0 (6233) KODI connected
2021-01-27 11:27:37.088  - [34mdebug[39m: kodi.0 (6233) GetPortWebServer: {"value":80}
2021-01-27 11:27:37.193  - [34mdebug[39m: kodi.0 (6233) GetNameVersion: 
[].... a lot - and I mean A LOT of stuff deleted ...]
2021-01-27 11:27:42.315  - [34mdebug[39m: kodi.0 (6233) Response isPlayerId: []
2021-01-27 11:27:44.275  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:27:46.298  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:27:48.326  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:27:50.378  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:27:52.429  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:27:54.464  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:27:56.536  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:27:58.636  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:00.688  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:02.743  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:04.805  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:06.828  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:08.904  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:10.926  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:12.983  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:15.021  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:17.086  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:19.109  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:21.158  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:23.183  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:25.207  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:27.232  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:29.256  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:31.293  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:33.321  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:35.342  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:37.356  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:39.403  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:41.429  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:43.451  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:45.477  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:47.498  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:49.522  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:51.535  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:53.555  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:55.583  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:57.609  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:28:59.630  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:01.648  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:03.669  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:05.696  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:07.717  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:09.740  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:11.757  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:13.788  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:15.807  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:17.829  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:19.855  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:21.885  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:23.909  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:25.926  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:27.943  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:29.952  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:31.963  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:33.981  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:36.000  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:38.010  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:40.020  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:42.037  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:44.072  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:46.083  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:48.094  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:50.109  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:52.124  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:54.133  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:56.150  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:29:58.170  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:00.126  - [32minfo[39m: host.Casper instance system.adapter.dwd.0 started with pid 9381
2021-01-27 11:30:00.191  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:02.202  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
[....]
2021-01-27 11:30:04.202  - [32minfo[39m: host.Casper instance system.adapter.daswetter.0 started with pid 9460
2021-01-27 11:30:04.208  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:06.216  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
[....]
2021-01-27 11:30:08.232  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:10.241  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:12.250  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:14.259  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:16.268  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:18.275  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:20.284  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:22.292  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:24.301  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:26.310  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:28.319  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:30.327  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:32.338  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:34.346  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:36.355  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:38.362  - [34mdebug[39m: kodi.0 (6233) Response GetPlayerId: []
2021-01-27 11:30:38.520  - [32minfo[39m: host.Casper stopInstance system.adapter.kodi.0 (force=false, process=true)
2021-01-27 11:30:38.523  - [32minfo[39m: host.Casper stopInstance system.adapter.kodi.0 send kill signal
2021-01-27 11:30:38.615  - [32minfo[39m: kodi.0 (6233) Got terminate signal TERMINATE_YOURSELF
2021-01-27 11:30:38.618  - [34mdebug[39m: kodi.0 (6233) cleaned everything up...
2021-01-27 11:30:38.620  - [32minfo[39m: kodi.0 (6233) terminating
2021-01-27 11:30:38.623  - [32minfo[39m: kodi.0 (6233) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-01-27 11:30:39.211  - [32minfo[39m: host.Casper instance system.adapter.kodi.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-01-27 11:30:41.606  - [32minfo[39m: host.Casper instance system.adapter.kodi.0 started with pid 10222
2021-01-27 11:30:45.471  - [32minfo[39m: kodi.0 (10222) starting. Version 2.0.4 in /opt/iobroker/node_modules/iobroker.kodi, node: v12.20.1, js-controller: 3.1.6
2021-01-27 11:30:50.856  - [32minfo[39m: kodi.0 (10222) KODI connected

```

**Comment by instalator** [comment]
Probably a problem with dns, specify the address in the ip settings.

**Comment by instalator** [comment]
fixed 2.0.5

**Comment by mediaDS** [comment]
No, it's not. Log:

```
2021-02-11 21:10:35.115 - info: harmony.0 (2212) hub busy, stateChange delayed: harmony.0.mediaDS.TV.PowerOff = 1
--
2021-02-11 21:10:35.104 - info: kodi.0 (666) sending in KODI: Player.Stop - {"playerid":null}
2021-02-11 21:10:35.140 - info: kodi.0 (666) sending in KODI: System.Shutdown - []
2021-02-11 21:10:35.379 - error: kodi.0 (666) uncaught exception: Unexpected token � in JSON at position 0
2021-02-11 21:10:35.383 - error: kodi.0 (666) SyntaxError: Unexpected token � in JSON at position 0
at JSON.parse ()
at WebSocket.promise.handle (/opt/iobroker/node_modules/jrpc-schema/lib/jrpc-schema.js:18:19)
at WebSocket.emit (events.js:314:20)
at Receiver.receiverOnMessage (/opt/iobroker/node_modules/kodi-ws/node_modules/ws/lib/websocket.js:825:20)
at Receiver.emit (events.js:314:20)
at Receiver.dataMessage (/opt/iobroker/node_modules/kodi-ws/node_modules/ws/lib/receiver.js:437:14)
at Receiver.getData (/opt/iobroker/node_modules/kodi-ws/node_modules/ws/lib/receiver.js:367:17)
at Receiver.startLoop (/opt/iobroker/node_modules/kodi-ws/node_modules/ws/lib/receiver.js:143:22)
at Receiver._write (/opt/iobroker/node_modules/kodi-ws/node_modules/ws/lib/receiver.js:78:10)
at doWrite (_stream_writable.js:403:12)
2021-02-11 21:10:35.384 - error: kodi.0 (666) Unexpected token � in JSON at position 0
2021-02-11 21:10:35.407 - info: kodi.0 (666) KODI connected
2021-02-11 21:10:35.439 - info: kodi.0 (666) terminating
2021-02-11 21:10:35.444 - warn: kodi.0 (666) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-02-11 21:10:36.159 - error: host.Casper instance system.adapter.kodi.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-02-11 21:10:36.161 - info: host.Casper Restart adapter system.adapter.kodi.0 because enabled
```

I tried IP numbers as well as hostnames. DNS and DHCP is  all working fine in my network. I got about 12 devices with either hostnames or IP numbers without any problems for years.

**Comment by instalator** [comment]
This log has a completely different error. We need a debug log of this error.

**Comment by instalator** [comment]
System.Shutdown is works
